book/urls.py
"""URLs book appObjektorientierte Scriptsprachen WS 2014Autoren: Beate Gericke, Gerrit Storm24.01.2015"""from django.conf.urls import patterns, urlfrom book import viewsurlpatterns = patterns('',    url(r'^$', views.index, name='index'),    url(r'^addauthor/$', views.addAuthor, name='addAuthor'),    url(r'^authors/$', views.authors, name='authorlist'),    url(r'^authors/(?P<page>[0-9]+)?/$', views.authors, name='authors'),    url(r'^editauthor/(?P<pk>[0-9]+)/$', views.addAuthor, name='editAuthor'),    url(r'^book/add/$', views.editBook, name='addBook'),    url(r'^book/edit/(?P<pk>[0-9]+)/$', views.editBook, name='editBook'),    url(r'^book/detail/(?P<pk>[0-9]+)/$', views.detailBook, name='detailBook'),    url(r'^book/comment/(?P<pk>[0-9]+)/$', views.commentBook, name='commentBook'),    url(r'^book/deleteComment/(?P<pk>[0-9]+)/(?P<bpk>[0-9]+)/$', views.deleteComment, name='deleteComment'),    url(r'^book/rate/(?P<pk>[0-9]+)/$', views.rateBook, name='rateBook'),    url(r'^book/own/(?P<pk>[0-9]+)/$', views.ownBook, name='ownBook'),    url(r'^books/$', views.books, name='booklist'),    url(r'^books/(?P<page>[0-9]+)?/$', views.books, name='books'),    url(r'^books/(?P<order>[a-z]+)?/$', views.setOrderBooks,  name='booksrating'),    url(r'^booksearch/$', views.setBookSearch,  name='booksearch'),    url(r'^booksfilter/$', views.setBookFilter,  name='booksfilter'),    url(r'^books/category/add$', views.addBookCategory,  name='book_category_add'),    url(r'^books/author/add$', views.addBookAuthor,  name='book_author_add'),)

film/urls.py
"""URLs film appObjektorientierte Scriptsprachen WS 2014Autoren: Beate Gericke, Gerrit Storm24.01.2015"""from django.conf.urls import patterns, urlfrom film import viewsurlpatterns = patterns('',    url(r'^$', views.index, name='index'),    url(r'^addparticipant/$', views.addParticipant, name='addParticipant'),    url(r'^participants/$', views.participants, name='participantlist'),    url(r'^participants/(?P<page>[0-9]+)?/$', views.participants, name='participants'),    url(r'^editparticipant/(?P<pk>[0-9]+)/$', views.addParticipant, name='editParticipant'),    url(r'^add/$', views.editFilm, name='addFilm'),    url(r'^edit/(?P<pk>[0-9]+)/$', views.editFilm, name='editFilm'),    url(r'^detail/(?P<pk>[0-9]+)/$', views.detailFilm, name='detailFilm'),    url(r'^film/comment/(?P<pk>[0-9]+)/$', views.commentFilm, name='commentFilm'),    url(r'^film/deleteComment/(?P<pk>[0-9]+)/(?P<bpk>[0-9]+)/$', views.deleteComment, name='deleteComment'),    url(r'^film/rate/(?P<pk>[0-9]+)/$', views.rateFilm, name='rateFilm'),    url(r'^film/own/(?P<pk>[0-9]+)/$', views.ownFilm, name='ownFilm'),    url(r'^films/$', views.films, name='filmlist'),    url(r'^films/(?P<page>[0-9]+)?/$', views.films, name='films'),    url(r'^films/(?P<order>[a-z]+)?/$', views.setOrderFilms,  name='filmsrating'),    url(r'^filmsearch/$', views.setFilmSearch,  name='filmsearch'),    url(r'^filmsfilter/$', views.setFilmFilter,  name='filmsfilter'),    url(r'^films/category/add$', views.addFilmCategory,  name='film_category_add'),    url(r'^films/participant/add$', views.addFilmParticipant,  name='film_participants_add'),)

medialib/urls.py
"""
URLs medialib Projekt
Autoren: Beate Gericke, Gerrit Storm
24.01.2015
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import  HttpResponseRedirect
from django.conf import settings
import settings

urlpatterns = patterns('',
    url(r'^$', 'medialib.views.index', name='home'),
    url(r'^film/', include('film.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^user/', include('userauth.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
)

film/models.py
"""
models film app
Objektorientierte Scriptsprachen WS 2014
Autoren: Beate Gericke, Gerrit Storm
24.01.2015
"""
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.db.models import Avg

""" Category
"""
@python_2_unicode_compatible
class Category(models.Model):
    categoryname = models.CharField('category', max_length=255)
    def __str__(self):
        return '%s' % (self.categoryname)

""" FilmComment
Kommentare zu Filmen
"""     
@python_2_unicode_compatible 
class FilmComment(models.Model):

    text = models.TextField('Kommentartext',  blank=False)
    user = models.ForeignKey(User, unique=False)
    film = models.ForeignKey('Film', unique=False)
    commentdate = models.DateTimeField(auto_now=True)
    def __str__(self):
        return '%s' % (self.text)
        
""" FilmOwning
Speicherung ob ein Benutzer ein Film gesehen hat oder besitzt
"""   
@python_2_unicode_compatible
class FilmOwning(models.Model):
    OWN = (
        ('Ja', 'Ja'),
        ('Nein', 'Nein'),
    )
    SEEN = (
        ('Ja', 'Ja'),
        ('Nein', 'Nein'),
    )
    own = models.CharField(max_length=15, choices = OWN, default = 'Nein' )
    seen = models.CharField(max_length=15, choices = SEEN, default = 'Nein' )
    user = models.ForeignKey(User, unique=False)
    film = models.ForeignKey('Film', unique=False)
    owningdate = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'Gehoert mir: %s, Habe ich gesehen: %s ' % (self.own, self.seen)
    class Meta:
        unique_together = (('user', 'film'),)     
        
""" Participant
"""
@python_2_unicode_compatible
class Participant(models.Model):
    CHOICE = (
    ('director', 'Regisseur'),
    ('writer', 'Autor'),
    ('star', 'Schauspieler'),
)
    firstname = models.CharField('lastname', max_length=255, )
    lastname = models.CharField('firstname', max_length=255, )
    role = models.CharField(max_length=40, choices=CHOICE)

    def __str__(self):
        return '%s, %s (%s)' % (self.lastname, self.firstname, self.role)

""" FilmRating
Speicherung der Bewertung eines Filmes
"""
@python_2_unicode_compatible
class FilmRating(models.Model):
    CHOICE = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)
    rating = models.IntegerField(max_length=1,default=1, choices=CHOICE)
    user = models.ForeignKey(User, unique=False)
    film = models.ForeignKey('Film', unique=False)
    ratingdate = models.DateTimeField(auto_now=True)
    def __str__(self):
        return '%s' % (self.rating)
    class Meta:
        unique_together = (('user', 'film'),)     
        
""" Film
"""
@python_2_unicode_compatible
class Film(models.Model):
    title = models.CharField( max_length=255, verbose_name=u'Titel')
    year = models.CharField( max_length=4,verbose_name=u'Jahr' )
    length = models.CharField( max_length=3,verbose_name=u'Spieldauer in Minuten' )
 
    description = models.TextField(u'Beschreibung', blank=True)
    participants  = models.ManyToManyField(Participant , verbose_name=u'Mitwirkende')
    categories = models.ManyToManyField(Category, verbose_name=u'Kategorien')
    cover = models.FileField(upload_to='cover/film/%Y%m%d', default='cover/default/default.png')
    
    filmtimestamp = models.DateTimeField(auto_now=True)
   
    def printCategories(self):
        categoryStr = ''
        for cat in self.categories.all():
            categoryStr = categoryStr + " " + str(cat)
        return categoryStr
           
    def orderRating(self):
        return FilmRating.objects.all().filter(film_id=self.id).aggregate(Avg('rating'))['rating__avg']
        

    def __str__(self):
        return self.title
    def printParticipant(self):
        return self.participants.all()
    def printAvgRating(self):
        filmRatings = FilmRating.objects.all().filter(film_id=self.id) 
        count = filmRatings.count()
        if count != 0:
            avg = ("%.1f" % round(filmRatings.aggregate(Avg('rating'))['rating__avg'],1))
            avg = avg + ' ('+str(count)+' Bewertungen)'
        else:
            avg = 'noch keine Bewertungen'
        
        return avg  

film/forms.py
"""
forms film app
Objektorientierte Scriptsprachen WS 2014
Autoren: Beate Gericke, Gerrit Storm
24.01.2015
"""
from django.forms import ModelForm
from django import forms
from film.models import *
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory
from django.utils.translation import ugettext_lazy as _


class ParticipantForm(ModelForm):
    class Meta:
        model = Participant

class FilmForm(ModelForm):
    year = forms.ChoiceField(choices=((str(x), x) for x in range(1940,2016)))
    length = forms.ChoiceField(choices=((str(x), x) for x in range(0,300)))
    class Meta:
        model = Film
        fields = ['title', 'year','length', 'description', 'cover', 'participants', 'categories']

class CategoryForm(ModelForm):
    class Meta:
        model = Category

class FilmCommentForm(ModelForm):
    class Meta:
        model = FilmComment
        fields = ['text', ]
        labels = {'text': _('Geben Sie Ihren Kommentar ein:'),}
        widgets = {
          'text': forms.Textarea(attrs={'rows':4, 'cols':15}),
        }

class FilmRatingForm(ModelForm):
    class Meta:
        model = FilmRating
        fields = ['rating', ]

class FilmOwningForm(ModelForm):
    class Meta:
        model = FilmOwning
        fields = ['own', 'seen',]
        labels = {
            'own': _('Gehoert mir'),
            'seen': _('Habe ich gesehen'),
        }

film/templates/film/addParticipant.html
{# Beate 02.01.2015#}
        {% extends 'base.html' %}
        {% load bootstrap3 %}
{# End Beate 02.01.2015 #}

{% block content %}
<h1>{{ page_title }}</h1>
     <form method="post" enctype="multipart/form-data" action="" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form participant_form layout='horizontal' %}
        {% buttons layout='horizontal' %}

        <button type="submit" class="btn btn-primary" name="submit" value="submit">
         {#% bootstrap_icon "star" %#} Submit
        </button>
         {% if not new %}
         <button type="submit" class="btn btn-primary" name="delete" value="delete">
         {#% bootstrap_icon "star" %#} Delete
        </button>
         {% endif %}
        {% endbuttons %}
    </form>
{% endblock %}

film/templates/film/film.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}


<script src="http://malsup.github.com/jquery.form.js"></script>
    <script> 
        $(document).ready(function() { 
        
            a = $('#formPA').ajaxForm(function() { 
                $('#InfoBox').css('visibility','visible');
                $('#btn_col').trigger('click');
                $('#id_firstname').val(""); 
                $('#id_lastname').val(""); 
                setTimeout(function() {
                        location.reload(); 
                }, 500);
               
            }); 
            c = $('#formCA').ajaxForm(function() {
                $('#InfoBox2').css('visibility','visible');
                $('#btn_col2').trigger('click');
                $('#id_categoryname').val("");      
                setTimeout(function() {
                    location.reload(); 
                }, 500);
            });           
        }); 
</script> 

<div class="custom-center-area-100">
    <h1>{{ page_title }}</h1>
    <form  method="post" enctype="multipart/form-data" action="" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form film_form layout='horizontal' %}
     
        <div style=" width:50%; margin-left:100px">
                <button type="submit" class="btn btn-primary" name="submit" value="submit">
                 {#% bootstrap_icon "star" %#} Speichern
                </button>
                {% if not new %} 
                <button type="submit" class="btn btn-primary" name="delete" value="delete">
                 {#% bootstrap_icon "star" %#} Löschen
                </button>
                {% endif %} 
           <a style="float:right; margin:right:200px" id="btn_col" class="btn btn-default" data-toggle="collapse" href="#a" aria-expanded="false" aria-controls="a">Mitwirkender</a>
                <span id="InfoBox" style="visibility:hidden; color:green; "> Mitwirkender angelegt!</span>
           <a style="float:right; margin:right:200px" id="btn_col2" class="btn btn-default" data-toggle="collapse" href="#c" aria-expanded="false" aria-controls="c">neue Kategorie</a>
                <span id="InfoBox2" style="visibility:hidden; color:green; "> Kategorie angelegt!</span>       
        </div>        
    </form>

<div class="collapse" id="a">
  <div class="well">
    <form id="formPA" method="post" enctype="multipart/form-data" action="{% url 'film_participants_add' %}" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form participant_form layout='horizontal' %}
        {% buttons layout='horizontal' %}

        <button type="submit" class="btn btn-primary">
         {#% bootstrap_icon "star" %#} Submit
        </button>
        {% endbuttons %}
    </form>
  </div>
</div>

<div class="collapse" id="c">
  <div class="well">
    <form id="formCA" method="post" enctype="multipart/form-data" action="{% url 'film_category_add' %}" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form category_form layout='horizontal' %}
        {% buttons layout='horizontal' %}

        <button type="submit" class="btn btn-primary">
         {#% bootstrap_icon "star" %#} Submit
        </button>
        {% endbuttons %}
    </form>
  </div>
</div>
</div>
{% endblock %}

film/templates/film/film_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}

<div class="row">
<div class=" col-md-10 col-sm-10 col-xs-10  col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
<div class="row">
    <div class="custom-book-cover col-md-3 col-sm-3 col-xs-3">
         <img src="{{MEDIA_URL}}{{film.cover}}" alt="Cover">
    </div>
    <div class="custom-book-details col-md-6 col-sm-6 col-xs-6">
        <h1>{{ film }}</h1>
        <p>
            <b>Kategorien:</b>
           {{ film.categories.all|join:', ' }}
        </p>
        <p>
            <b>Spieldauer: </b>
            {{ film.length }}
        </p>

        <p> <b>Beschreibung: </b></p><p>{{ film.description }}</p>
        <p> <b>Jahr: </b>{{ film.year }}</p>
         <p>
             <b>Mitwirkende:</b><br>
        {% for participant in film.participants.all%}
             <span style="margin-right:10px;" >{{ participant }}</span><br>
        {% endfor %}
        </p>
    </div>

    
    <div class="custom-book-add col-md-3 col-sm-3 col-xs-3">
    {# Bewertung des Filmes #}
        <b>Durchschnittliche Bewertung: {{ film.printAvgRating }}</b><br>
        {% if user.is_authenticated %}
        <div>
        {% if ownRating == 0 %}

            <b>Sie haben diesen Film noch nicht bewertet:</b>
            <form class="form-inline" role="form" method="post" action="{% url 'rateFilm' pk=film.id %}" >
                <div class="form-group">
                {% for field in form2%}
                {{ field }}
                {% endfor %}
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="float:left">
                         bewerten
                    </button>
               </div>
            </form>
        {% else %}
            <b>Sie haben dieses Film schon  bewertet: {{ ownRating }}</b>
        {% endif %}
        </div>
        {# Ende Bewertung des Filmes #}

        <div>
            {% if owning == 0 %}
            <br><br>
            <b>Geben Sie an, ob Sie diesen Film besitzen und ob Sie es bereits gesehen haben:</b>
            <form class="form-inline" role="form" method="post" action="{% url 'ownFilm' pk=film.id %}" >
                {% csrf_token %}
                {% bootstrap_form form3 layout='inline' %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" style="float:left">
                             speichern
                        </button>
                   </div>
             </form>
            {% else %}
            <b>Sie haben ihre Angaben schon gemacht:<br> </b>
            <span>Film gehört mir: {{ owning.own }}</span><br>
            <span>Film gelesen: {{ owning.seen }}</span>
            {% endif %}
        </div>
        {% endif %}
    </div>
    

</div><!-- end row -->
</div>
</div>

<div class="row" style="margin-top: 25px;">
<div class=" col-md-10 col-sm-10 col-xs-10  col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
<div class="custom-comment-area">
<hr>
<h2>Kommentare:</h2>
<hr>

    {% if user.is_authenticated %}
<form  action="{% url 'commentFilm' pk=film.id %}" method="post" accept-charset="utf-8">
    {% bootstrap_form form %}
    {% csrf_token %}
    
    {% buttons %}
        <button type="submit" class="btn btn-primary" style="float:left">
            {#% bootstrap_icon "star" %#} Kommetieren
        </button>
   {% endbuttons %}
  
</form>
    {% else %}
    <b>Sie müssen eingeloggt sein, um Kommentare abgeben zu können.</b>
    {% endif %}
</div>
<br><br><hr>
      <div class="container-fluid">
     <div class="row">
     <div class="col-md-12 col-md-offset-0">
    {% for comment in comments%}

        <div class="custom-comment">

            <div class="row comment-head">
                <div class="col-md-8">
                    {{comment.user.username}}
                </div>
                <div class="col-md-4 comment-date">
                    {{comment.commentdate|date:'d.m.Y H:i'}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    {{comment.text}}
                </div>
            </div>
            {% if perms.change_filmcomment %}
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'deleteComment' pk=comment.pk bpk=film.pk  %}" type="submit" name="delete" value="delete"  class="btn btn-default">
                        Löschen
                    </a>
                </div>
            </div>
            {% endif %}
        </div>

    {% endfor %}
     </div>
     </div>
     </div>
</div>
</div>
{% endblock %}

film/templates/film/filmlist.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}
<div class="custom-center-area-70">
    <h1 style="display: inline; ">Liste der Filme </h1>
       <div   class="custom-head-area" > 
           <div   style="width:40%; float:left; "> 
               <form style=" " method="post"  role="" action="{% url 'filmsearch'  %}">
                    {% csrf_token %}
                    <div class="form-group">
                            <input style="float:left; width:60%" name="search" maxlength="20" type="text" class="form-control" placeholder="Titel Suche">
                    </div>
                    <button style="display:float:left;" type="submit" class="btn btn-default">Suchen</button>
                </form>
            </div> 
             <div   style="width:40%; float:right; "> 

               <form style=" " method="post"  role="" action="{% url 'filmsfilter'  %}">
                    {% csrf_token %}
                    <div class="form-group">
                            <select style="float:left;  width:60%" name="filter"  class="form-control">
                                <option></option>
                                <option>gesehen</option>
                                <option>nicht gesehen</option>
                            </select>
                    </div>
                    <button style="display:float:left;" type="submit" class="btn btn-default">Filter</button>
                </form>
     
            </div> 
           <div   style="width:40%; float:left; "> 
            {% if TitelSearch != '' %} 
            <p><b>Suchbegriff: {{TitelSearch}} </b></p>
            <form  style="display: inline; " method="post"  role="" action="{% url 'filmsearch'  %}">
               {% csrf_token %}
               <input name="search" type="hidden" class="form-control" placeholder="Titel Suche">
                <button style="display: inline; " type="submit" class="btn btn-default">Suche Löschen</button>
            </form>
          {% endif %}
          </div> 
          
          <div   style="width:40%; float:right; "> 
           {% if filter != '' %} 
            <p><b>Filter: {{filter}} </b></p>
            <form  style="display: inline; " method="post"  role="" action="{% url 'filmsfilter'  %}">
               {% csrf_token %}
               <input name="search" type="hidden" class="form-control" placeholder="Titel Suche">
                <button style="display: inline; " type="submit" class="btn btn-default">Filter Löschen</button>
            </form>
           {% endif %}
           </div> 
           
        
         </div> <!-- head area -->
       
        <table class="table">
            <tr>            
                <th>
                <a href="{% url 'filmsrating' order='title' %}" >Title<a> 
                {% if orderBy == 'title' %}
                <img src="{{STATIC_URL}}img/{{orderImg}}.gif" alt="."> </img></th>
                {% endif %}
                <th><a href="{% url 'filmsrating' order='year' %}" >Jahr</a>
                {% if orderBy == 'year' %}
                <img src="{{STATIC_URL}}img/{{orderImg}}.gif" alt="."> </img></th>
                {% endif %}</th>
                
                <th>
                 <a href="{% url 'filmsrating' order='length' %}" >Spieldauer<a>
                {% if orderBy == 'length' %}
                <img src="{{STATIC_URL}}img/{{orderImg}}.gif" alt="."> </img>
                {% endif %}
                </th>
                
                <th>Kategorie</th>
                <th>
                <a href="{% url 'filmsrating' order='rating' %}" >Bewertungen<a>
                {% if orderBy == 'rating' %}
                <img src="{{STATIC_URL}}img/{{orderImg}}.gif" alt="."> </img>
                {% endif %}
                </th>
                <th> 
                {% if perms.add_film %}
                <a href="{% url 'addFilm' %}" class="btn btn-primary">neuer Film</a>
                {% endif %}
                </th>
            </tr>
    {% for film in films%}
        <tr>
            <td><a href="{% url 'detailFilm' pk=film.pk %}">{{ film.title }}</a></td>
            <td>
                {{ film.year }}
            </td>
            <td> 
                {{ film.length }}
            </td>
            <td> 
                {{ film.printCategories }}
            </td>
            <td>

                <p>{{ film.printAvgRating }}</p>
             
            </td>
            <td>
                {% if perms.add_film %}
                <a href="{% url 'editFilm' pk=film.pk %}">{% bootstrap_icon 'edit' %}</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
        </table>

    {% if number > 0 %}
    <nav>
        <ul class="pagination">
            <li {% if 1 == page %} class="disabled" {% endif %}>
                <a  href="{% url 'films' page=1  %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
    {% for count in pageRange %}
            <li {% if count == page %} class="active" {% endif %}><a  href="{% url 'films' page=count  %}">{{count}}</a></li>
    {% endfor %}
            <li {% if pageNum == page %} class="disabled" {% endif %}>
                <a href="{% url 'films' page=pageNum  %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    {% else %}
        <br><br>
            <b> Nichts gefunden!</b>
        <br><br>
    {% endif %}
 
</div>
{% endblock %}

film/templates/film/participantlist.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}
<div class="custom-center-area-70">
        <h1>Liste der Mitwirkenden</h1>
        <table class="table">
            <tr>
                <th>Nachname</th>
                <th>Vorname</th>
                <th>Rolle</th>
                <th>        {% if perms.add_author %}
        <a href="{% url 'addParticipant' %}" class="btn btn-primary">neuer Mitwirkender</a>
        {% endif %}</th>
            </tr>

    {% for participant in participants%}
        <tr>
            <td>
                {{ participant.lastname }}
            </td>
            <td>
                {{ participant.firstname }}
            </td>
             <td>
                {{ participant.role }}
            </td>
            <td>
                {% if perms.edit_participant %}
                <a href="{% url 'editParticipant' pk=participant.pk %}">{% bootstrap_icon 'edit' %}</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
        </table>
        
<nav>
  <ul class="pagination">
    <li {% if 1 == page %} class="disabled" {% endif %}>
      <a  href="{% url 'authors' page=1  %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
      
    {% for count in pageRange %}
        <li {% if count == page %} class="active" {% endif %}><a  href="{% url 'authors' page=count  %}">{{count}}</a></li>
    {% endfor %}
    
    <li {% if pageNum == page %} class="disabled" {% endif %}>
      <a href="{% url 'authors' page=pageNum  %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    
    
  </ul>
</nav>    
</div>
{% endblock %}